pipeline {
    agent {
        docker { image 'maven:3.8-openjdk-11' }
    }
    stages {
        stage('Build with Maven') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Run Java Program') {
            steps {
                java -jar target/hello-world-1.0-SNAPSHOT.jar

            }
        }
    }
}


      
